#
# Configuration
#
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 10

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

#
# Build Lifecycle:
#

before_install:
  - nvm install node 10
  - nvm use node 10
  - npm install -g typescript
  - npm install -g karma-cli
  - npm install -g webpack
  # - ionic state clear # Deprecate: remove from ionic >3.0.0
  - npm install -g webdriver-manager
  - webdriver-manager update

install: npm install


script:
  - npm run test:ci
  # - ionic build broewser --prod
  # - protractor test-config/protractor.conf.js      # run e2e tests against ionic
